---
name: Dependabot Auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Fetch Metadata from Dependabot PRs
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}

      - run: gh pr merge "$PR" --rebase
        env:
          PR: ${{github.event.pull_request.number}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
