---
name: Dependabot Auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - run: gh pr merge "$PR" --rebase
        env:
          PR: ${{github.event.pull_request.number}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

