---
name: Dependabot Auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - run: gh pr merge "$PR" --squash
        env:
          PR: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
